spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/codetech?characterEncoding=UTF-8&serverTimezone=UTC
    username: codetech11
    password: c*o@d$et#ec$h11

#jwt:
#  secret-key:
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 420